services:
  - type: web
    name: summative
    env: python
    repo: https://github.com/brianmposwayo-prog/Summative
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
